### ISSUE TITLE
Error: could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'

### ISSUE THREAD

**Issue by saivenkateshedem** [gtsystem/lightkube#35]
Getting the error from the below code

 config = KubeConfig.from_file("/tmp/kubeconfig")
 
kubeconfig
-------------
{'apiVersion': ('v1',), 'clusters': [{'cluster': {'server': '<url>', 'certificate-authority-data': '<data>'}, 'name': 'kubernetes'}], 'contexts': [{'context': {'cluster': 'kubernetes', 'user': 'aws'}, 'name': 'aws'}], 'current-context': 'aws', 'Kind': 'config', 'users': [{'name': 'aws', 'user': 'lambda'}]}

**Comment by gtsystem** [comment]
[saivenkateshedem](https://github.com/saivenkateshedem), `KubeConfig.from_file` takes as a parameter a file in YAML format as it's needed for `kubectl`. Your example seems to not be conform to such standard.

I'll keep open this issue as indeed the documentation is not clear on this regard.
