### ISSUE TITLE
Add means to compare quantities

### ISSUE THREAD

**Issue by sed-i** [gtsystem/lightkube#36]
## Background

K8s converts user input [quantities](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/) to "canonical form":

> Before serializing, Quantity will be put in "canonical form". This means that Exponent/suffix will be adjusted up or down (with a corresponding increase or decrease in Mantissa) such that: a. No precision is lost b. No fractional digits will be emitted c. The exponent (or suffix) is as large as possible. The sign will be omitted unless the number is negative.
>
> Examples: 1.5 will be serialized as "1500m" 1.5Gi will be serialized as "1536Mi"

Additional examples:

| User input                       | K8s representation            |
|----------------------------------|-------------------------------|
| `{"memory": "0.9Gi"}`            | `{"memory": "966367641600m"}` |
| `{"cpu": "0.30000000000000004"}` | `{"cpu": "301m"}`             |

## Use case

When patching a statefulset's resource limits, it would be handy to be able to compare a quantity's setpoint 

```
statefulset.spec.template.spec.containers[i].resources
```

to the active podspec

```
pod.spec.containers[i].resources
```

Currently, two equivalent `ResourceRequirements` instances could differ under `==` comparison and require manual interconversion.

## Additional thoughts
- k8s-client has a [`parse_quantity`](https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/quantity.py) function, but having both lightkube and kubernetes deps is not ideal.
- [bitmath](https://pypi.org/project/bitmath/) doesn't support millis and is awkward to "abuse" for cpu values.
- Implementing [comparisons](https://peps.python.org/pep-0207/) for `class ResourceRequirements` might be ackward.

**Comment by gtsystem** [comment]
Yes, a function similar to `parse_quantity` could be a good addition. Would you like to contribute a PR?
