### ISSUE TITLE
Resources fetched via list operation have apiVersion and kind fields set to None

### ISSUE THREAD

**Issue by benfiola** [gtsystem/lightkube#65]
Hey there!  

When I list resources using the lightkube async client, the resources that are returned are missing their _apiVersion_ and _kind_ fields. 

This might be because the underlying kubernetes list apis return `*List` resources whose members actually don't have these fields populated - but I figure I'd let you know to see how you'd want to proceed.

## Environment

* python 3.10.12
* lightkube 0.15.3
* lightkube-models 1.30.0.8

## Example

```
import asyncio
import pathlib

import lightkube.config.kubeconfig
import lightkube.core.async_client
from lightkube.resources.core_v1 import Service


async def main():
    config = lightkube.config.kubeconfig.KubeConfig.from_file(
        pathlib.Path("/root/.kube/config")
    )
    kube_client = lightkube.core.async_client.AsyncClient(config)
    async for item in kube_client.list(Service):
        assert item.apiVersion is None
        assert item.kind is None


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by gtsystem** [comment]
I'm not sure that fixing the issue in all the clients is the way to go, it would be better to have this fixed in kubernetes itself (kubernetes/kubernetes#3030). However if this is blocking you in some way, I guess it's fine to have a temporary fix in place.

**Comment by benfiola** [comment]
Yeah, it's probably something that _should_ be handled by kubernetes - but it looks like the [various](https://github.com/kubernetes/kubernetes/pull/80618) [PRs](https://github.com/kubernetes/kubernetes/pull/63972) that have been opened to address it ever landed.  It's unclear why there's no momentum behind landing those changes (could be low priority, could be complicated)

Ultimately, this isn't blocking me (I can always patch in the behavior if I need it on my end) - just felt like trying to tackle the problem after filing the issue.  :D

**Comment by benfiola** [comment]
Closing the issue - thanks (again) for the merge!
