### ISSUE TITLE
Add `__init__.py` to generated `resources` folder

### ISSUE THREAD

**Issue by max-muoto** [gtsystem/lightkube#71]
Thanks for this library! Just creating this issue, because I'm having some issues with type-checker warnings importing from the generated `resources` directory. The lack of an `__init__.py` causes some type-checkers not to recognize it as properly stubbed.

**Comment by gtsystem** [comment]
Hi, the `__init__.py` file as been added as part of the release of the new models for k8s v1.31 `lightkube-models==1.31.1.8`

**Comment by max-muoto** [comment]
> Hi, the `__init__.py` file as been added as part of the release of the new models for k8s v1.31 `lightkube-models==1.31.1.8`

Thanks!
