### ISSUE TITLE
Please support source distributions on PyPi

### ISSUE THREAD

**Issue by balbirthomas** [gtsystem/lightkube#9]
## Use case
Cross platform deployments of software systems that depend on lightkube may want to build it from source for a specific platform before deploying. 

## Issue
At present only prebuilt wheels are available [through PyPi](https://pypi.org/project/lightkube/#files)

**Comment by gtsystem** [comment]
All right, I released v0.8.1 also as tar.gz. Will do the same for the models later today

**Comment by balbirthomas** [comment]
Closing since this issue is now resolved. Thank you very much.
